# Generated by Django 4.0.1 on 2022-01-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetApi.category'),
        ),
    ]
